site_name: Penguor Documentation
theme:
  name: material
  font: 
    code:
      Fira Code

  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
  
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # icons
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo:
      fontawesome/brands/github

# plugins

plugins: 
  - git-revision-date
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

# repository
repo_url: https://github.com/Penguor/PenguorDocs
repo_name: Penguor/PenguorDocs
edit_uri: edit/main/docs/

# social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Penguor
      name: Penguor on GitHub

#navigation
nav:
  - Penguor: 
    - 'index.md'
    - 'Penguor/What_is_Penguor.md'
    - 'Penguor/FAQ.md'
  - Language Specification:
    - Language_Specification/index.md
    - Collections:
      - Language_Specification/Collections/index.md
      - Language_Specification/Collections/Arrays.md
    - Access Modifiers:
      - Language_Specification/Modifiers/Access_Modifiers.md
      - Language_Specification/Modifiers/Non_Access_Modifiers.md
    - Data Types:
      - Built-in Types:
        - Language_Specification/Data_Types/Built-in_Types/Bool.md
      - Language_Specification/Data_Types/index.md
      - Language_Specification/Data_Types/Custom_Data_Types.md
      - Language_Specification/Data_Types/Groups.md
    - Messages:
      - Language_Specification/Messages/Penguor-debugmsg.md
      - Language_Specification/Messages/PenguorCS-debugmsg.md
  - Developer Documentation:
    - 'Developer_Documentation/index.md'
    - Developer_Documentation/Design_Considerations.md
  